#+Title: Hemaratings Scraper

* About
The script scrapes hemaratings.com, specifically the lists of /events/, /clubs/, /fighters/ and /rankings/ and saves the information locally in a SQLite3 database.

* Installation of dependencies
1. Clone the repository locally via https (=git clone https://Eurydice86/hemaratings_scrape=) or ssh (=git clone git@github.com:Eurydice86/hemaratings_scrape.git=)
2. Install the dependencies (=pip install -r requirements.txt=). You might want to create a virtual environment (=python -m venv <name>=) and activate it first.
* Usage
Run =python scrape.py= followed by the appropriate flags, depending on what you want to scrape.
Run =python scrape.py -h= for help.

** Flags
-h, --help      show the help message and exit
-f, --fighters  scrape fighters
-c, --clubs     scrape clubs
-e, --events    scrape events
-r, --ratings   scrape ratings
--history       scrape the full history of ratings (only works if -r is active)

i.e., if running =python scrape.py -fcer --history=, gets the full data, including historical (monthly) rankings and ratings for each of the available weapon categories.

* Disclaimer
This is a by no means perfect version of the scraper. It is working as of March 2025, but updates/additions to the hemaratings pages might cause it to break.
